#ifndef METIN2_CLIENT_MAIN_PYTHONEMOJIMANAGER_H
#define METIN2_CLIENT_MAIN_PYTHONEMOJIMANAGER_H

#include <Config.hpp>

#if VSTD_HAS_PRAGMA_ONCE
#pragma once
#endif

#endif /* METIN2_CLIENT_MAIN_PYTHONEMOJIMANAGER_H */
