/*
 Navicat Premium Data Transfer

 Source Server         : Win64Local
 Source Server Type    : MariaDB
 Source Server Version : 110302 (11.3.2-MariaDB)
 Source Host           : localhost:3306
 Source Schema         : common

 Target Server Type    : MariaDB
 Target Server Version : 110302 (11.3.2-MariaDB)
 File Encoding         : 65001

 Date: 03/05/2024 23:36:01
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for events
-- ----------------------------
DROP TABLE IF EXISTS `events`;
CREATE TABLE `events`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `period` enum('DAILY','WEEKLY','MONTHLY','ANNUALLY') CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `type` enum('FLAG','OX','PVP','GUILD','MONARCH','GOLD_EVENT') CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL,
  `details` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `map_index` int(11) NOT NULL DEFAULT 41,
  `channel` int(11) NOT NULL DEFAULT 1,
  `start_time` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `end_time` int(11) NOT NULL,
  `is_notice` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = Aria AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of events
-- ----------------------------

-- ----------------------------
-- Table structure for gmconfig
-- ----------------------------
DROP TABLE IF EXISTS `gmconfig`;
CREATE TABLE `gmconfig`  (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `authority` enum('IMPLEMENTOR','GOD','HIGH_WIZARD','WIZARD','LOW_WIZARD','PLAYER') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT 'PLAYER',
  `general_allow` set('GM_ALLOW_DROP_PLAYER_ITEM','GM_ALLOW_DROP_GM_ITEM','GM_ALLOW_EXCHANGE_PLAYER_ITEM_TO_GM','GM_ALLOW_EXCHANGE_PLAYER_ITEM_TO_PLAYER','GM_ALLOW_EXCHANGE_GOLD_TO_PLAYER','GM_ALLOW_EXCHANGE_GM_ITEM_TO_GM','GM_ALLOW_EXCHANGE_GM_ITEM_TO_PLAYER','GM_ALLOW_EXCHANGE_GOLD_TO_GM','GM_ALLOW_EXCHANGE_TO_GM','GM_ALLOW_EXCHANGE_TO_PLAYER','GM_ALLOW_EXCHANGE_ANTIGIVE','GM_ALLOW_BUY_PRIVATE_ITEM','GM_ALLOW_CREATE_PRIVATE_SHOP','GM_ALLOW_USE_SAFEBOX','GM_ALLOW_CREATE_PLAYER','GM_ALLOW_DELETE_PLAYER','GM_ALLOW_MODIFY_OTHERS','GM_ALLOW_ADMIN_MANAGER','GM_ALLOW_SPECIAL_NAMES','GM_ALLOW_BUFF_GM_TO_PLAYER','GM_ALLOW_BUFF_PLAYER_TO_GM','GM_ALLOW_PLAYER_GUILD_INVITE','GM_ALLOW_GM_GUILD_INVITE','GM_ALLOW_PLAYER_GROUP_INVITE','GM_ALLOW_GM_GROUP_INVITE','GM_ALLOW_ADD_PLAYER_AS_FRIEND','GM_ALLOW_ADD_GM_AS_FRIEND') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '',
  `manager_allow` set('ALLOW_VIEW_ONLINE_LIST','ALLOW_VIEW_ONLINE_COUNT','ALLOW_GM_TRADE_BLOCK_OPTION','ALLOW_MAPVIEWER','ALLOW_VIEW_MAPVIEWER_NPC','ALLOW_VIEW_MAPVIEWER_STONE','ALLOW_VIEW_MAPVIEWER_MONSTER','ALLOW_VIEW_MAPVIEWER_PLAYER','ALLOW_VIEW_MAPVIEWER_ORE','ALLOW_OBSERVER','ALLOW_VIEW_OBSERVER_GOLD','ALLOW_VIEW_OBSERVER_SKILL','ALLOW_VIEW_OBSERVER_EQUIPMENT','ALLOW_VIEW_OBSERVER_INVENTORY','ALLOW_VIEW_OBSERVER_WHISPER','ALLOW_OBSERVER_CHATBAN','ALLOW_OBSERVER_ACCOUNTBAN','ALLOW_OBSERVER_PERMA_ACCOUNTBAN','ALLOW_BAN','ALLOW_VIEW_BAN_CHAT','ALLOW_VIEW_BAN_CHAT_LOG','ALLOW_BAN_CHAT','ALLOW_VIEW_BAN_ACCOUNT','ALLOW_VIEW_BAN_ACCOUNT_LOG','ALLOW_BAN_ACCOUNT','ALLOW_ITEM','ALLOW_VIEW_ITEM') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `mDisplayInFriendlist`(`general_allow`) USING BTREE
) ENGINE = Aria AUTO_INCREMENT = 26 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of gmconfig
-- ----------------------------
INSERT INTO `gmconfig` VALUES (18, 'IMPLEMENTOR', 'GM_ALLOW_DROP_PLAYER_ITEM,GM_ALLOW_DROP_GM_ITEM,GM_ALLOW_EXCHANGE_PLAYER_ITEM_TO_GM,GM_ALLOW_EXCHANGE_PLAYER_ITEM_TO_PLAYER,GM_ALLOW_EXCHANGE_GOLD_TO_PLAYER,GM_ALLOW_EXCHANGE_GM_ITEM_TO_GM,GM_ALLOW_EXCHANGE_GM_ITEM_TO_PLAYER,GM_ALLOW_EXCHANGE_GOLD_TO_GM,GM_ALLOW_EXCHANGE_TO_GM,GM_ALLOW_EXCHANGE_TO_PLAYER,GM_ALLOW_EXCHANGE_ANTIGIVE,GM_ALLOW_BUY_PRIVATE_ITEM,GM_ALLOW_CREATE_PRIVATE_SHOP,GM_ALLOW_USE_SAFEBOX,GM_ALLOW_CREATE_PLAYER,GM_ALLOW_DELETE_PLAYER,GM_ALLOW_MODIFY_OTHERS,GM_ALLOW_SPECIAL_NAMES,GM_ALLOW_BUFF_GM_TO_PLAYER,GM_ALLOW_BUFF_PLAYER_TO_GM,GM_ALLOW_PLAYER_GUILD_INVITE,GM_ALLOW_GM_GUILD_INVITE,GM_ALLOW_PLAYER_GROUP_INVITE,GM_ALLOW_GM_GROUP_INVITE,GM_ALLOW_ADD_PLAYER_AS_FRIEND,GM_ALLOW_ADD_GM_AS_FRIEND', 'ALLOW_VIEW_BAN_CHAT,ALLOW_VIEW_BAN_CHAT_LOG,ALLOW_BAN_CHAT');
INSERT INTO `gmconfig` VALUES (21, 'PLAYER', 'GM_ALLOW_DROP_PLAYER_ITEM,GM_ALLOW_DROP_GM_ITEM,GM_ALLOW_EXCHANGE_PLAYER_ITEM_TO_PLAYER,GM_ALLOW_EXCHANGE_GOLD_TO_PLAYER,GM_ALLOW_EXCHANGE_GOLD_TO_GM,GM_ALLOW_EXCHANGE_TO_GM,GM_ALLOW_EXCHANGE_TO_PLAYER,GM_ALLOW_EXCHANGE_ANTIGIVE,GM_ALLOW_BUY_PRIVATE_ITEM,GM_ALLOW_CREATE_PRIVATE_SHOP,GM_ALLOW_USE_SAFEBOX,GM_ALLOW_CREATE_PLAYER,GM_ALLOW_DELETE_PLAYER,GM_ALLOW_PLAYER_GUILD_INVITE,GM_ALLOW_PLAYER_GROUP_INVITE,GM_ALLOW_ADD_PLAYER_AS_FRIEND', '');
INSERT INTO `gmconfig` VALUES (22, 'LOW_WIZARD', 'GM_ALLOW_DROP_PLAYER_ITEM,GM_ALLOW_EXCHANGE_GOLD_TO_GM,GM_ALLOW_CREATE_PLAYER,GM_ALLOW_DELETE_PLAYER', 'ALLOW_VIEW_BAN_CHAT,ALLOW_VIEW_BAN_CHAT_LOG,ALLOW_BAN_CHAT');
INSERT INTO `gmconfig` VALUES (23, 'WIZARD', 'GM_ALLOW_DROP_PLAYER_ITEM,GM_ALLOW_EXCHANGE_GOLD_TO_GM,GM_ALLOW_CREATE_PLAYER,GM_ALLOW_DELETE_PLAYER', 'ALLOW_VIEW_BAN_CHAT,ALLOW_VIEW_BAN_CHAT_LOG,ALLOW_BAN_CHAT');
INSERT INTO `gmconfig` VALUES (24, 'HIGH_WIZARD', 'GM_ALLOW_DROP_PLAYER_ITEM,GM_ALLOW_EXCHANGE_GOLD_TO_GM,GM_ALLOW_CREATE_PLAYER,GM_ALLOW_DELETE_PLAYER', 'ALLOW_VIEW_BAN_CHAT,ALLOW_VIEW_BAN_CHAT_LOG,ALLOW_BAN_CHAT');
INSERT INTO `gmconfig` VALUES (25, 'GOD', 'GM_ALLOW_DROP_PLAYER_ITEM,GM_ALLOW_EXCHANGE_GOLD_TO_GM,GM_ALLOW_CREATE_PLAYER,GM_ALLOW_DELETE_PLAYER', 'ALLOW_VIEW_BAN_CHAT,ALLOW_VIEW_BAN_CHAT_LOG,ALLOW_BAN_CHAT');

-- ----------------------------
-- Table structure for gmhost
-- ----------------------------
DROP TABLE IF EXISTS `gmhost`;
CREATE TABLE `gmhost`  (
  `mIP` varchar(16) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT ''
) ENGINE = Aria CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of gmhost
-- ----------------------------

-- ----------------------------
-- Table structure for gmlist
-- ----------------------------
DROP TABLE IF EXISTS `gmlist`;
CREATE TABLE `gmlist`  (
  `mID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mAccount` varchar(32) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `mName` varchar(32) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `mContactIP` varchar(16) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `mServerIP` varchar(16) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'ALL',
  `mSalt` varchar(32) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `mAuthority` enum('IMPLEMENTOR','GOD','HIGH_WIZARD','WIZARD','LOW_WIZARD','PLAYER') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT 'PLAYER',
  `mDisplayInFriendlist` tinyint(1) NULL DEFAULT 0,
  `mLang` set('hu','pl','cz','de','ro','tr','es','en','pt','it') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT 'en',
  PRIMARY KEY (`mID`) USING BTREE,
  INDEX `mDisplayInFriendlist`(`mDisplayInFriendlist`) USING BTREE
) ENGINE = Aria AUTO_INCREMENT = 4 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of gmlist
-- ----------------------------
INSERT INTO `gmlist` VALUES (3, 'adalet', 'Adalet', '', 'ALL', NULL, 'IMPLEMENTOR', 1, 'en');

-- ----------------------------
-- Table structure for locale
-- ----------------------------
DROP TABLE IF EXISTS `locale`;
CREATE TABLE `locale`  (
  `mKey` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `mValue` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`mKey`) USING BTREE
) ENGINE = Aria CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of locale
-- ----------------------------

-- ----------------------------
-- Table structure for spam_db
-- ----------------------------
DROP TABLE IF EXISTS `spam_db`;
CREATE TABLE `spam_db`  (
  `type` set('GOOD','SPAM') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'SPAM',
  `word` varchar(256) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `score` int(11) NOT NULL DEFAULT 10,
  PRIMARY KEY (`word`) USING BTREE
) ENGINE = Aria CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of spam_db
-- ----------------------------

SET FOREIGN_KEY_CHECKS = 1;
