#pragma once

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED		= 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,			// 205
	AFFECT_CON,	
	AFFECT_INT,	
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,		// 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,	// 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,		// 220
	AFFECT_MOUNT,

	// This one is obsolete
	//AFFECT_WAR_FLAG, // 222

	AFFECT_BLOCK_CHAT,		// 223
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,	// 225
	AFFECT_DEF_GRADE,		// 226


	AFFECT_BLEEDING,		// 229

	AFFECT_ATT_SPEED_SLOW,
	AFFECT_ATT_GRADE_DOWN,
	AFFECT_DEF_GRADE_DOWN,
	AFFFECT_CRITICAL_PCT_DOWN,
	AFFECT_MOUNT_FALL,
	AFFECT_NO_RECOVERY,
	AFFECT_REDUCE_CAST_SPEED,

	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING = 301,

	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,

	AFFECT_PREMIUM_START	= 500,
	AFFECT_EXP_BONUS		= 500,	// 경험의 반지
	AFFECT_ITEM_BONUS		= 501,	// 도둑의 장갑
	AFFECT_SAFEBOX		= 502,  // PREMIUM_SAFEBOX,
	AFFECT_AUTOLOOT		= 503,	// PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND		= 504,	// PREMIUM_FISH_MIND,
	AFFECT_MARRIAGE_FAST	= 505,	// 원앙의 깃털
	AFFECT_GOLD_BONUS		= 506,	// 돈 드롭확률 50%증가
	AFFECT_SHOP_DOUBLE_UP	= 507,
	AFFECT_VOTE_BONUS		= 508,
	AFFECT_PREMIUM_END		= 509,

	AFFECT_MALL			= 510,	// 몰 아이템 에펙트
	AFFECT_NO_DEATH_PENALTY	= 511,	// 용신의 가호 (경험치가 패널티를 한번 막아준다)
	AFFECT_SKILL_BOOK_BONUS	= 512,	// 선인의 교훈 (책 수련 성공 확률이 50% 증가)
	AFFECT_SKILL_NO_BOOK_DELAY	= 513,	// 주안술서

	AFFECT_HAIR	= 514,	// 헤어 효과
	AFFECT_COLLECT = 515, //수집퀘스트 
	AFFECT_EXP_BONUS_EURO_FREE = 516, // 경험의 반지 (유럽 버전 14 레벨 이하 기본 효과)
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,
#ifdef ENABLE_BATTLE_PASS
	AFFECT_BATTLE_PASS,
#endif
	AFFECT_PREMIUM_SWITCHBOT = 520,

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,

	AFFECT_BLEND,

	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,

	AFFECT_AUTO_HP_RECOVERY,
	AFFECT_AUTO_SP_RECOVERY,
	AFFECT_PREVENT_GOOD,

	AFFECT_WAR_FLAG_1,
	AFFECT_WAR_FLAG_2,
	AFFECT_WAR_FLAG_3,

	AFFECT_DASH,

	AFFECT_DRAGON_SOUL_QUALIFIED,
	AFFECT_DRAGON_SOUL_DECK_0,
	AFFECT_DRAGON_SOUL_DECK_1,
	AFFECT_DS_SET,
	
	AFFECT_VOTE_BONUS2,
	AFFECT_VOTE_BONUS3,
	AFFECT_VOTE_BONUS4,

	AFFECT_NON_OBSERVER,
	AFFECT_SHADOW_POTION,
	AFFECT_EPIC,

#if defined(WJ_COMBAT_ZONE)	
	AFFECT_COMBAT_ZONE_POTION = 585,
	AFFECT_COMBAT_ZONE_DEFENSE = 586,
	AFFECT_COMBAT_ZONE_MOVEMENT = 587,
#endif

#ifdef ENABLE_HYDRA_DUNGEON
	AFFECT_HYDRA = 603,
#endif

#ifdef ENABLE_MELEY_LAIR_DUNGEON
	AFFECT_STATUE_1 = 700,
	AFFECT_STATUE_2 = 701,
	AFFECT_STATUE_3 = 702,
	AFFECT_STATUE_4 = 703,
#endif

	AFFECT_QUEST_START_IDX = 1000
};

enum EAffectSubTypes {
    AFFECT_TYPE_NORMAL,
	AFFECT_TYPE_REAL_TIME,
};

inline bool IsRealTimeAffect(uint32_t type)
{
	switch (type) {
	case AFFECT_PREMIUM_SWITCHBOT:
		return true;
    default: break;
	}

	return false;
}

inline bool IsSkipSaveAffect(uint32_t type)
{
	switch (type) {
	case AFFECT_WAR_FLAG_1:
	case AFFECT_WAR_FLAG_2:
	case AFFECT_WAR_FLAG_3:
	case AFFECT_REVIVE_INVISIBLE:
	case AFFECT_DASH:
		return true;
	}

	return type >= AFFECT_PREMIUM_START && type <= AFFECT_PREMIUM_END;
}

inline bool IsRetainOnDeathAffect(uint32_t type)
{
	if (type == AFFECT_BLOCK_CHAT)
		return true;

	if(type == 152) // Guild TP Skill
		return true;

	// Note: Since this is a skill, it has to vanish on death.
	if (type == AFFECT_PREVENT_GOOD)
		return false;

	if (type >= AFFECT_MOV_SPEED && type < AFFECT_FISH_MIND_PILL)
		return true;

	if(type >= AFFECT_QUEST_START_IDX)
		return true;

	if(type < 200)
		return true;

	return type >= 500 && type < 600;
}


enum AffectVariable
{
	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
