#ifndef METIN2_GAME_DUNGEONINFOCONSTANTS_HPP
#define METIN2_GAME_DUNGEONINFOCONSTANTS_HPP

#include <Config.hpp>

#if VSTD_HAS_PRAGMA_ONCE
#pragma once
#endif

enum EDungeonList
{
	DUNGEON_ID_NONE,
	DUNGEON_ID_OWL,
	DUNGEON_ID_GARDEN,
	DUNGEON_ID_DEEP_CAVE,
	DUNGEON_ID_NEVERLAND,
	DUNGEON_ID_WOOD,
	DUNGEON_ID_ICESTORM,
	DUNGEON_ID_SHADOW_TOWER,
	DUNDEON_ID_PYRA,
	DUNGEON_ID_DEMON,
	DUNGEON_ID_SLIME_1,
	DUNGEON_ID_SLIME_2,
	DUNGEON_ID_SLIME_3,
	DUNGEON_ID_SLIME_4,
	DUNGEON_ID_RATHALOS_1,
	DUNGEON_ID_MAX,
};

enum EDungeonRankingType
{
	DUNGEON_RANK_TYPE_COUNT,
	DUNGEON_RANK_TYPE_TIME,
	DUNGEON_RANK_TYPE_DMG,
	DUNGEON_RANK_TYPE_MAX,
	
	DUNGEON_RANKING_MAX_NUM = 10,
};

#endif