#pragma once 

#include "Constants.hpp"

enum
{
	EMOTICON_EXCLAMATION = 1,
	EMOTICON_FISH = 11,
	EMOTICON_NUM = 128,

	TITLE_NUM = 62,
	TITLE_NONE = 35,
};


enum EEffectKind
{
	EFFECT_KIND_NONE,
	EFFECT_KIND_MOTION_EFFECT,
	EFFECT_KIND_MOTION_EFFECT_TO_TARGET,
	EFFECT_KIND_AFFECT,
	EFFECT_KIND_FLY,
	EFFECT_KIND_ATTACHING,
	EFFECT_KIND_SMOKE,
	EFFECT_KIND_SHINING,
	EFFECT_KIND_REFINED,
	EFFECT_KIND_EMOTION,
	EFFECT_KIND_BATTLE,
	EFFECT_KIND_SPECIAL_EFFECT,
	EFFECT_KIND_MISC,
        EFFECT_KIND_SHINING_PERSIST,
};

enum
{
	EFFECT_DUST,
	EFFECT_STUN,
	EFFECT_HIT,
	EFFECT_FLAME_ATTACK,
	EFFECT_FLAME_HIT,
	EFFECT_FLAME_ATTACH,
	EFFECT_ELECTRIC_ATTACK,
	EFFECT_ELECTRIC_HIT,
	EFFECT_ELECTRIC_ATTACH,
	EFFECT_SPAWN_APPEAR,
	EFFECT_SPAWN_DISAPPEAR,
	EFFECT_LEVELUP,
	EFFECT_SKILLUP,
	EFFECT_HPUP_RED,
	EFFECT_SPUP_BLUE,
	EFFECT_SPEEDUP_GREEN,
	EFFECT_DXUP_PURPLE,
	EFFECT_CRITICAL,
	EFFECT_PENETRATE,
	EFFECT_BLOCK,
	EFFECT_DODGE,
	EFFECT_FIRECRACKER,
	EFFECT_SPIN_TOP,
	EFFECT_WEAPON,
	EFFECT_WEAPON_ONEHANDED,
	EFFECT_WEAPON_TWOHANDED,
	EFFECT_WEAPON_DUALHANDED,

	EFFECT_EMOTICON,
	EFFECT_EMOTICON_END = EFFECT_EMOTICON + EMOTICON_NUM,
	EFFECT_SELECT,
	EFFECT_TARGET,
	EFFECT_EMPIRE,
	EFFECT_EMPIRE_END = EFFECT_EMPIRE + EMPIRE_MAX_NUM,
	EFFECT_HORSE_DUST,

	EFFECT_SWORD_REFINED7,
	EFFECT_SWORD_REFINED8,
	EFFECT_SWORD_REFINED9,

	EFFECT_BOW_REFINED7,
	EFFECT_BOW_REFINED8,
	EFFECT_BOW_REFINED9,

	EFFECT_FANBELL_REFINED7,
	EFFECT_FANBELL_REFINED8,
	EFFECT_FANBELL_REFINED9,

	EFFECT_FANBELL_REFINED7_LEFT,
	EFFECT_FANBELL_REFINED8_LEFT,
	EFFECT_FANBELL_REFINED9_LEFT,

	EFFECT_SMALLSWORD_REFINED7,
	EFFECT_SMALLSWORD_REFINED8,
	EFFECT_SMALLSWORD_REFINED9,



	EFFECT_SMALLSWORD_REFINED7_LEFT,
	EFFECT_SMALLSWORD_REFINED8_LEFT,
	EFFECT_SMALLSWORD_REFINED9_LEFT,

	EFFECT_CLAW_REFINED7,
	EFFECT_CLAW_REFINED8,
	EFFECT_CLAW_REFINED9,

	EFFECT_CLAW_REFINED7_LEFT,
	EFFECT_CLAW_REFINED8_LEFT,
	EFFECT_CLAW_REFINED9_LEFT,

	EFFECT_BODYARMOR_REFINED7,
	EFFECT_BODYARMOR_REFINED8,
	EFFECT_BODYARMOR_REFINED9,

	EFFECT_BODYARMOR_SPECIAL,	// °©¿Ê 4-2-1
	EFFECT_BODYARMOR_SPECIAL2,	// °©¿Ê 4-2-2

	EFFECT_BODYARMOR_SPECIAL3,	//  5-1

#ifdef EVILLON_REFINE_EFFECTS
	EFFECT_BODYARMOR_LOVE,
	EFFECT_BODYARMOR_BLACK,
	EFFECT_BODYARMOR_WHITE,
	EFFECT_BODYARMOR_RED,
	EFFECT_BODYARMOR_VIP,
	EFFECT_BODYARMOR_EPIC,
#endif
	EFFECT_DAMAGE_TARGET,
	EFFECT_DAMAGE_NOT_TARGET,
	EFFECT_DAMAGE_SELFDAMAGE,
	EFFECT_DAMAGE_SELFDAMAGE2,
	EFFECT_DAMAGE_POISON,
	EFFECT_DAMAGE_MISS,
	EFFECT_DAMAGE_TARGETMISS,
	EFFECT_DAMAGE_CRITICAL,
	EFFECT_SUCCESS,
	EFFECT_FAIL,
	EFFECT_FR_SUCCESS,
	EFFECT_LEVELUP_ON_14_FOR_GERMANY,	//·¹º§¾÷ 14ÀÏ¶§ ( µ¶ÀÏÀü¿ë )
	EFFECT_LEVELUP_UNDER_15_FOR_GERMANY,//·¹º§¾÷ 15ÀÏ¶§ ( µ¶ÀÏÀü¿ë )
	EFFECT_PERCENT_DAMAGE1,
	EFFECT_PERCENT_DAMAGE2,
	EFFECT_PERCENT_DAMAGE3,
	EFFECT_AUTO_HPUP,
	EFFECT_AUTO_SPUP,
	EFFECT_RAMADAN_RING_EQUIP,			// ÃÊ½Â´Þ ¹ÝÁö Âø¿ë ¼ø°£¿¡ ¹ßµ¿ÇÏ´Â ÀÌÆåÆ®
	EFFECT_HALLOWEEN_CANDY_EQUIP,		// ÇÒ·ÎÀ© »çÅÁ Âø¿ë ¼ø°£¿¡ ¹ßµ¿ÇÏ´Â ÀÌÆåÆ®
	EFFECT_HAPPINESS_RING_EQUIP,				// Çàº¹ÀÇ ¹ÝÁö Âø¿ë ¼ø°£¿¡ ¹ßµ¿ÇÏ´Â ÀÌÆåÆ®
	EFFECT_LOVE_PENDANT_EQUIP,				// Çàº¹ÀÇ ¹ÝÁö Âø¿ë ¼ø°£¿¡ ¹ßµ¿ÇÏ´Â ÀÌÆåÆ®
	EFFECT_ACCE_SUCESS_ABSORB,
	EFFECT_ACCE_EQUIP,
	EFFECT_ACCE_BACK,
	EFFECT_EASTER_CANDY_EQIP,
	EFFECT_THUNDER_AREA,
	EFFECT_THUNDER,
	EFFECT_HEAL,
	EFFECT_CAPE_OF_COURAGE,
	EFFECT_CHOCOLATE_PENDANT,
	EFFECT_FEATHER_WALK,
	EFFECT_PEPSI_EVENT,
	EFFECT_DRAGONLAIR_STONE_UNBEATABLE_1,
	EFFECT_DRAGONLAIR_STONE_UNBEATABLE_2,
	EFFECT_DRAGONLAIR_STONE_UNBEATABLE_3,
	EFFECT_BATTLE_POTION,
	EFFECT_REFLECT,
	EFFECT_SKILL_DAMAGE_ZONE,
	EFFECT_SKILL_SAFE_ZONE,
	EFFECT_METEOR,
	EFFECT_BEAD_RAIN,
	EFFECT_ARROW_RAIN,
	EFFECT_FALL_ROCK,
	EFFECT_HORSE_DROP,
	EFFECT_EGG_DROP,
	EFFECT_DEAPO_BOOM,
	EFFECT_FLOWER_EVENT,
	EFFECT_GEM_PENDANT,
	EFFECT_DEFENSE_WAVE_LASER,
	EFFECT_PET_ATTR_CHANGE_NEW_TYPE,
	EFFECT_PET_PAY_SUMMON1,
	EFFECT_SPECAIL_ROULETTE,

	EFFECT_CAPE_EQIP,
	EFFECT_GM,
	EFFECT_SGM,
	EFFECT_SA,

	EFFECT_TEMP,
	EFFECT_NUM,
};
