/*
Author: Adalet 
Filename: Services.hpp
Project Name: Diamas SF Project
Last Revision: 26.03.2024
*/
#ifndef METIN2_SERVICES_HPP
#define METIN2_SERVICES_HPP
#pragma once

/** Improvement Defines **/
#define SAS_KEY "!#b9nGZp"
#define __PET_SYSTEM__
#define __UDP_BLOCK__

/** General and System Defines **/
#define INGAME_WIKI
#define ENABLE_DS_SET
#define ENABLE_HYDRA_DUNGEON
#define ENABLE_BATTLE_PASS
#define ENABLE_PERSPECTIVE_VIEW
#define RUBINU_NO_POTIONS
#define ENABLE_INPUT_CANCEL
#define ENABLE_COSTUME_SYSTEM
#define ENABLE_ENERGY_SYSTEM
#define ENABLE_DRAGON_SOUL_SYSTEM
#define ENABLE_NEW_EQUIPMENT_SYSTEM
#define NON_CHECK_DS_QUALIFIED
#define ENABLE_CUBE_TRANSFER_BONUSES
#define ENABLE_CUBE_SELECT_REMOVE_ITEMS_ON_FAILURE
#define ENABLE_SHINING_SYSTEM
#define ENABLE_DESTROY_ITEM_SYSTTEM
#define ENABLE_DICE_SYSTEM
#define ENABLE_NEW_USER_CARE
#define ENABLE_12ZI
#define ENABLE_CHANGE_LOOK_ITEM_SYSTEM
#define ENABLE_CHANGE_LOOK_SYSTEM
#define ENABLE_ACCE_SECOND_COSTUME_SYSTEM
#define ENABLE_DETAILS_UI
#define ENABLE_CHANGED_ATTR
#define ENABLE_ELEMENT_ADD
#define NEW_SELECT_CHARACTER
#define WJ_ENABLE_TRADABLE_ICON
#define WJ_MULTI_TEXTLINE
#define WJ_NEW_USER_CARE
#define LOGIN_COUNT_DOWN_UI_MODIFY
#define WJ_SHOW_PARTY_ON_MINIMAP
#define ENABLE_PARTY_CHANNEL_FIX
#define POPUPDIALOG_MODIFY
#define ENABLE_ENVIRONMENT_EFFECT_OPTION
#define ENABLE_MOVE_COSTUME_ATTR
#define ENABLE_MYSHOP_DECO
#define ENABLE_AFFECT_POLYMORPH_REMOVE
#define ENABLE_CUBE_CHANCE_CONFIRMATION
#define ENABLE_ACCE_COSTUME_SYSTEM
#define NON_CHECK_DRAGON_SOUL_QUALIFIED
#define ENABLE_MOUNT_COSTUME_SYSTEM
#define WJ_SHOW_MOB_INFO
#define WJ_SHOW_SHOP_CONTROLLER
#define WJ_SHOW_ACCE_ONOFF
#define WJ_ENABLE_PICKUP_ITEM_EFFECT
#define ENABLE_ANTI_CHANGE_ATTR
#define ENABLE_SPECULAR_ONOFF
#define ENABLE_678TH_SKILL
#define ENABLE_ALWAYS_INSTANT_DEATH
#define INSTINCT_BUILD
#define __HACKFIX_WALLHACK__  4
#define __WORLD_BOSS__
#define __COOL_REFRESH_EDITLINE__
#define __WJ_SHOW_MOB_INFO__
#define __HIGHLIGHT_DROPPED_ITEMS__
#define __OFFLINE_MESSAGE__
#define __DUNGEON_FOR_GUILD__
#ifdef __DUNGEON_FOR_GUILD__
#define ENABLE_MELEY_LAIR_DUNGEON
#ifdef ENABLE_MELEY_LAIR_DUNGEON
#define MELEY_LAIR_DUNGEON_STATUE 6118
#define __DESTROY_INFINITE_STATUES_GM__
#define __LASER_EFFECT_ON_75HP__
#define __LASER_EFFECT_ON_50HP__
#endif
#endif
#define ENABLE_PLAYTIME_ICON
#define NEW_PICK_UP_ITEM
#define ENABLE_NEW_GUILD_WAR
#define ENABLE_GUILD_WAR_BEGIN
#define ENABLE_GUILD_START_LEVEL
#define ENABLE_FLY_MOUNT
#define ENABLE_GAMEMASTER_TEXTAIL

/** Advanced Sync Fixes **/
#define ENABLED_SLIDING_SYNC_FOR_JOB_INSTANCE
#define ENHANCED_FLY_FIX
#define ENHANCED_SYNC_UPDATE
#define ENABLE_CLIENT_AUTH_ACCOUNT_REGISTER


/** OfflineShop Defines **/
#define __OFFLINE_SHOP__
#ifdef __OFFLINE_SHOP__
#define __SPECIAL_OFFLINE_SHOP_WHISPER__
#ifdef __SPECIAL_OFFLINE_SHOP_WHISPER__
#define OFFLINE_SHOP_NPC_RACE 30008
#endif
#define __OFFLINE_SHOP_FARM_OPENING_TIME__
#define __OFFLINE_SHOP_CHANGE_NAME_DELAY__
#define __OFFLINE_SHOP_CLOSE_ITEMS_TO_INVENTORY__
#define __OFFLINE_SHOP_DISALLOW_MANUAL_POSITIONING__
#define __OFFLINE_SHOP_LOGGING__
#define __OFFLINE_SHOP_CLOSE_BY_COMMAND__
#define __OFFLINE_SHOP_USE_BUNDLE__
#if defined(__OFFLINE_SHOP_OPENING_TIME__) && defined(__OFFLINE_SHOP_FARM_OPENING_TIME__)
#error Defining both identifiers is not allowed: __OFFLINE_SHOP_OPENING_TIME__, __OFFLINE_SHOP_FARM_OPENING_TIME__
#endif
#endif
#define ENABLE_PRIVATESHOP_SEARCH_SYSTEM
#define ENABLE_PRIVATESHOP_SYSTEM_ALWAYS_SILK
#define DISABLE_PRIVATE_SHOP_SEARCH_NEED_ITEM
#define DISABLE_PRIVATE_SHOP_NEED_ITEM
#define PRIVATE_SHOP_OPENING_PRICE 10000


/** Special Defines **/
#ifdef ENABLE_CYTHON
	#define __USE_CYTHON__
#endif
#define __NEW_GAMEMASTER_CONFIG__
#define DISABLE_METIN_STONE_DROP

#if defined(_WIN32) || defined(_WIN64)
#define _WIN_VRUNNER_ // Windows icin vrunner 
#endif

/** Closed Defines **/
//#define __FAKE_PC__
//#define L3_EAZY
//#define ENABLE_WOLFMAN_CHARACTER
//#define ENABLE_GUILD_STORAGE
//#define ENABLE_PLAYER_PER_ACCOUNT5
//#define ENABLE_GUILD_STORAGE
//#define ENABLE_MOVE_COSTUME_ATTR_BONUS_LIMIT
//#define ENABLE_GEM_SYSTEM
//#define ENABLE_PVM_BOOST_FOR_SHAMAN_AND_NINJA
// ENABLE_NEMERE_DUNGEON_EXTRAS
//#define ENABLE_AUTOMATIC_EVENT_MANAGER
//#define ENABLE_GUILD_STORAGE
//#define ENABLE_SKILLBOOK_COMBINATION
//#define ENABLE_GEM_SYSTEM
#ifdef ENABLE_GEM_SYSTEM
#define GEM_MAX 999999
#endif

#endif